version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: moex_postgres
    environment:
      POSTGRES_DB: moex_oltp
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: moex_clickhouse
    environment:
      CLICKHOUSE_DB: moex_olap
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: admin123
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./clickhouse/init.sql:/docker-entrypoint-initdb.d/init.sql
      - clickhouse_data:/var/lib/clickhouse

volumes:
  postgres_data:
  clickhouse_data: